/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fantasydrafter.hmi;

import java.awt.Color;
import javax.swing.JToggleButton;

/**
 *
 * @author cbachich
 */
public class PickPanel extends javax.swing.JPanel {

  JToggleButton activeButton;
  
  /**
   * Creates new form PickPanel
   */
  public PickPanel() {
    initComponents();
  }
  
  // Change the color of the active pick
  public void activatePick(int pick) {
    
    // If the active button is not null then deactivate it
    if(activeButton != null) {
      setInactive(activeButton);
    }
    
    // Switch the pick
    switch(pick) {
      case 1:
        setActive(oneButton);
        activeButton = oneButton;
        break;
      case 2:
        setActive(twoButton);
        activeButton = twoButton;
        break;
      case 3:
        setActive(threeButton);
        activeButton = threeButton;
        break;
      case 4:
        setActive(fourButton);
        activeButton = fourButton;
        break;
      case 5:
        setActive(fiveButton);
        activeButton = fiveButton;
        break;
      case 6:
        setActive(sixButton);
        activeButton = sixButton;
        break;
      case 7:
        setActive(sevenButton);
        activeButton = sevenButton;
        break;
      case 8:
        setActive(eightButton);
        activeButton = eightButton;
        break;
      case 9:
        setActive(nineButton);
        activeButton = nineButton;
        break;
      case 10:
        setActive(tenButton);
        activeButton = tenButton;
        break;
    }
  }
  
  // Highlights the pick button yellow
  private void setActive(JToggleButton button) {
    button.setBackground(Color.yellow);
  }
  
  // Un-higlight the button
  private void setInactive(JToggleButton button) {
    button.setBackground(new java.awt.Color(193, 203, 193));
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    oneButton = new javax.swing.JToggleButton();
    twoButton = new javax.swing.JToggleButton();
    threeButton = new javax.swing.JToggleButton();
    fourButton = new javax.swing.JToggleButton();
    fiveButton = new javax.swing.JToggleButton();
    sixButton = new javax.swing.JToggleButton();
    sevenButton = new javax.swing.JToggleButton();
    eightButton = new javax.swing.JToggleButton();
    nineButton = new javax.swing.JToggleButton();
    tenButton = new javax.swing.JToggleButton();

    oneButton.setBackground(new java.awt.Color(193, 203, 193));
    oneButton.setFont(new java.awt.Font("Ubuntu", 1, 34)); // NOI18N
    oneButton.setForeground(new java.awt.Color(25, 25, 112));
    oneButton.setText("1");

    twoButton.setBackground(new java.awt.Color(193, 203, 193));
    twoButton.setFont(new java.awt.Font("Ubuntu", 1, 34)); // NOI18N
    twoButton.setForeground(new java.awt.Color(25, 25, 112));
    twoButton.setText("2");

    threeButton.setBackground(new java.awt.Color(193, 203, 193));
    threeButton.setFont(new java.awt.Font("Ubuntu", 1, 34)); // NOI18N
    threeButton.setForeground(new java.awt.Color(25, 25, 112));
    threeButton.setText("3");

    fourButton.setBackground(new java.awt.Color(193, 203, 193));
    fourButton.setFont(new java.awt.Font("Ubuntu", 1, 34)); // NOI18N
    fourButton.setForeground(new java.awt.Color(25, 25, 112));
    fourButton.setText("4");

    fiveButton.setBackground(new java.awt.Color(193, 203, 193));
    fiveButton.setFont(new java.awt.Font("Ubuntu", 1, 34)); // NOI18N
    fiveButton.setForeground(new java.awt.Color(25, 25, 112));
    fiveButton.setText("5");

    sixButton.setBackground(new java.awt.Color(193, 203, 193));
    sixButton.setFont(new java.awt.Font("Ubuntu", 1, 34)); // NOI18N
    sixButton.setForeground(new java.awt.Color(25, 25, 112));
    sixButton.setText("6");

    sevenButton.setBackground(new java.awt.Color(193, 203, 193));
    sevenButton.setFont(new java.awt.Font("Ubuntu", 1, 34)); // NOI18N
    sevenButton.setForeground(new java.awt.Color(25, 25, 112));
    sevenButton.setText("7");

    eightButton.setBackground(new java.awt.Color(193, 203, 193));
    eightButton.setFont(new java.awt.Font("Ubuntu", 1, 34)); // NOI18N
    eightButton.setForeground(new java.awt.Color(25, 25, 112));
    eightButton.setText("8");

    nineButton.setBackground(new java.awt.Color(193, 203, 193));
    nineButton.setFont(new java.awt.Font("Ubuntu", 1, 34)); // NOI18N
    nineButton.setForeground(new java.awt.Color(25, 25, 112));
    nineButton.setText("9");

    tenButton.setBackground(new java.awt.Color(193, 203, 193));
    tenButton.setFont(new java.awt.Font("Ubuntu", 1, 34)); // NOI18N
    tenButton.setForeground(new java.awt.Color(25, 25, 112));
    tenButton.setText("10");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(oneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(twoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(fourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(fiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(sixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(sevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(eightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(nineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(tenButton, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(oneButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(twoButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(threeButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(fourButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(fiveButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(sixButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(sevenButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(nineButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
          .addComponent(eightButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(tenButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JToggleButton eightButton;
  private javax.swing.JToggleButton fiveButton;
  private javax.swing.JToggleButton fourButton;
  private javax.swing.JToggleButton nineButton;
  private javax.swing.JToggleButton oneButton;
  private javax.swing.JToggleButton sevenButton;
  private javax.swing.JToggleButton sixButton;
  private javax.swing.JToggleButton tenButton;
  private javax.swing.JToggleButton threeButton;
  private javax.swing.JToggleButton twoButton;
  // End of variables declaration//GEN-END:variables
}
